### ISSUE TITLE
MAC address license check failure on WSL-2

### ISSUE THREAD

**Issue by bergtwvd** [hlacontainers/pitch-crc#3]
When the CRC container runs on WSL-2, federates get the following license error. On standard Linux kernels the CRC container runs fine.

````
orbat_1          | Exception in thread "main" hla.rti1516e.exceptions.RTIinternalError: Invalid hardware for this license.
orbat_1          |      at se.pitch.prti1516e.lrc.c.a(prticore_b3360:254)
orbat_1          |      at se.pitch.prti1516e.lrc.m.a(prticore_b3360:266)
orbat_1          |      at se.pitch.prti1516e.lrc.I.joinFederationExecution(prticore_b3360:331)
orbat_1          |      at se.pitch.prti1516e.lrc.G.joinFederationExecution(prticore_b3360:737)
orbat_1          |      at se.pitch.prti1516e.lrc.J.joinFederationExecution(prticore_b3360:1107)
orbat_1          |      at oorti.OORTIambassadorImpl.joinFederationExecution(OORTIambassadorImpl.java:206)
orbat_1          |      at oorti.OORTIambassadorImpl.joinFederationExecution(OORTIambassadorImpl.java:272)
orbat_1          |      at javalin.JavalinRTIambassadorImpl.join(JavalinRTIambassadorImpl.java:145)
orbat_1          |      at nl.tno.hla_orbat_server.OrbatApp.start(OrbatApp.java:88)
orbat_1          |      at nl.tno.hla_orbat_server.OrbatApp.main(OrbatApp.java:168)
````

**Comment by bergtwvd** [comment]
Adding the APT package net-tools to the image resolved the issue.
